# Generated by Django 5.0 on 2023-12-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
