# Generated by Django 5.0 on 2023-12-14 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airport_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Kelaasor Airports'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Kelaasor Flights'},
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='number',
            field=models.CharField(max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(help_text='price in Rial'),
        ),
    ]
