# Generated by Django 5.0 on 2023-12-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainstation',
            name='city',
            field=models.CharField(choices=[('TEH', 'Tehran'), ('ISF', 'Isfahan'), ('MSH', 'Mashhad'), ('KRJ', 'Karaj'), ('DEZ', 'Dezful')], max_length=255),
        ),
    ]
