# Generated by Django 5.0 on 2023-12-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('price', models.FloatField()),
                ('origin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='bus.terminal')),
            ],
        ),
    ]
