# Generated by Django 5.0 on 2023-12-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='bus.terminal'),
        ),
    ]
